import { Geist, Geist_Mono, Roboto } from "next/font/google";
import "./globals.css";
import { CartProvider } from "@/context/CartContext";
import ToastProvider from "@/components/common/ToastProvider";
import { AuthProvider } from "@/context/AuthContext";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

const roboto = Roboto({
  subsets: ['vietnamese', 'latin'],
  weight: ['100', '300', '400', '500', '700', '900'],
  style: ['normal', 'italic'],
  display: 'swap',
  variable: '--font-roboto',
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="vi" className={roboto.className}>
      <body className={`${geistSans.variable} ${geistMono.variable} antialiased`}>
        <ToastProvider />
        <AuthProvider>
          <CartProvider>
            {children}
          </CartProvider>
        </AuthProvider>

      </body>
    </html>
  );
}
