version: '3.8'

services:
  # 4. Elasticsearch (Tìm kiếm toàn văn)
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:8.10.2
    container_name: ecom_elasticsearch
    environment:
      - discovery.type=single-node
      - xpack.security.enabled=false
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
    ports:
      - "9200:9200"
    volumes:
      - es_data:/usr/share/elasticsearch/data
    deploy:
      resources:
        limits:
          cpus: '1.0'
          memory: 800M # Khóa chặt ở 800MB, không cho lấn sang RAM của IntelliJ

volumes:
  mysql_data:
  es_data:
