spring:
  config:
    import: optional:classpath:application-secret.yaml
  application:
    name: clothingstore
  datasource:
    url: jdbc:mysql://localhost:3306/clothingstore_db?useSSL=false&serverTimezone=UTC&allowPublicKeyRetrieval=true
    username: root          # <--- Sửa user
    password: Tuan171204@     # <--- Sửa pass
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update      # Tự động sinh/sửa bảng khi chạy code
    show-sql: true          # Hiện câu SQL ra log để debug cho dễ
    properties:
      hibernate:
        format_sql: true    # Format SQL cho đẹp
        dialect: org.hibernate.dialect.MySQL8Dialect

api:
  prefix: /api/v1


# Cấu hình VNPay
payment:
  vnpay:
    url: "https://sandbox.vnpayment.vn/paymentv2/vpcpay.html"
    return-url: "http://localhost:3000/payment-result" # Frontend nhận kết quả ở đây