spring:
  application:
    name: clothingstore
  datasource:
    url: jdbc:mysql://localhost:3306/clothingstore_db?useSSL=false&serverTimezone=UTC&allowPublicKeyRetrieval=true
    username: root          # <--- Sửa user
    password: Tuan171204@     # <--- Sửa pass
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: update      # Tự động sinh/sửa bảng khi chạy code
    show-sql: true          # Hiện câu SQL ra log để debug cho dễ
    properties:
      hibernate:
        format_sql: true    # Format SQL cho đẹp
        dialect: org.hibernate.dialect.MySQL8Dialect

api:
  prefix: /api/v1

cloudinary:
  cloud-name: ${CLOUDINARY_NAME}  # <--- Thay bằng Cloud Name
  api-key: ${CLOUDINARY_API_KEY}      # <--- Thay bằng API Key
  api-secret: ${CLOUDINARY_SECRET}   # <--- Thay bằng API Secret

# Cấu hình VNPay
payment:
  vnpay:
    url: "https://sandbox.vnpayment.vn/paymentv2/vpcpay.html"
    tmn-code: ${VNPAY_TMN_CODE}
    hash-secret: ${VNPAY_HASH_SECRET}  # <--- Paste vnp_HashSecret vào đây
    return-url: "http://localhost:3000/payment-result" # Frontend nhận kết quả ở đây